"""Generate demo data for the Agent Bazaar live trade playback."""

from __future__ import annotations

import argparse
import hashlib
import json
import time
from pathlib import Path
from typing import Any

from agents.lib.matching import rank_quotes
from schemas.quote import Erc8004ReputationSnapshot, QuoteMessage
from schemas.rfq import Budget, Constraints, RFQMessage, Task, TaskType

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "demo" / "market-trace-data.js"


def _hash_content(content: dict[str, object]) -> str:
    body = json.dumps(content, sort_keys=True, separators=(",", ":")).encode()
    return "0x" + hashlib.sha3_256(body).hexdigest()


def _quote(
    *,
    rfq_id: str,
    seller: str,
    price: int,
    confidence: float,
    success_rate: float,
    total_tasks: int,
    delivery_ms: int,
) -> QuoteMessage:
    return QuoteMessage(
        rfq_id=rfq_id,
        seller_agent_id=seller,
        seller_axl_peer_id=f"peer-{seller[-6:]}",
        quote_price_atomic=price,
        confidence_score=confidence,
        estimated_delivery_ms=delivery_ms,
        erc8004_reputation=Erc8004ReputationSnapshot(
            total_tasks=total_tasks,
            success_rate=success_rate,
            on_chain_proof_uri=f"erc8004://agent/{seller}",
        ),
        signature=f"demo-signature-{seller[-6:]}",
    )


def build_market_trace(*, now: int | None = None) -> dict[str, Any]:
    """Build one deterministic market trace using real project schemas.

    The data is intentionally stable so the board can be screen-recorded, while
    the scores still come from `agents.lib.matching.rank_quotes`.
    """
    timestamp = now or int(time.time())
    rfq = RFQMessage(
        rfq_id="0xa98c4345f5ec4ddfb36d7d3bdcf16c8000000000000000000000000000000",
        buyer_agent_id="0xB000000000000000000000000000000000000001",
        buyer_axl_peer_id="buyer-peer-demo",
        task=Task(
            type=TaskType.DATA_FETCH,
            input={
                "pair": "ETH/USDC",
                "prompt": "Fetch spot price and 24h volume from a reliable source.",
            },
            output_schema={
                "type": "object",
                "required": ["pair", "price", "volume_24h", "source"],
            },
        ),
        budget=Budget(
            max_usdc_atomic=500_000,
            accepted_tokens=["MockUSDC", "ETH", "USDC"],
        ),
        constraints=Constraints(min_reputation_score=0.8, deadline_unix=timestamp + 600),
        signature="demo-rfq-signature",
    )

    quotes = [
        _quote(
            rfq_id=rfq.rfq_id,
            seller="0xA111111111111111111111111111111111111111",
            price=420_000,
            confidence=0.91,
            success_rate=0.957,
            total_tasks=47,
            delivery_ms=2800,
        ),
        _quote(
            rfq_id=rfq.rfq_id,
            seller="0xB222222222222222222222222222222222222222",
            price=300_000,
            confidence=0.85,
            success_rate=0.88,
            total_tasks=18,
            delivery_ms=4100,
        ),
        _quote(
            rfq_id=rfq.rfq_id,
            seller="0xC333333333333333333333333333333333333333",
            price=260_000,
            confidence=0.74,
            success_rate=0.71,
            total_tasks=9,
            delivery_ms=2300,
        ),
    ]
    ranked = rank_quotes(rfq, quotes)
    winner = ranked[0].quote

    content = {
        "pair": "ETH/USDC",
        "price": 3412.15,
        "volume_24h": 1234567890,
        "source": "agent-bazaar-seller",
        "timestamp": timestamp,
    }
    result_hash = _hash_content(content)

    return {
        "generated_at": timestamp,
        "source": {
            "mode": "local_project_playback",
            "description": (
                "Generated by Agent Bazaar code: schemas/rfq.py, schemas/quote.py, "
                "and agents/lib/matching.py. Live sponsor calls are tested separately."
            ),
            "connected_to": ["RFQ schema", "Quote schema", "matching algorithm"],
            "not_connected_to": ["live AXL inbox", "live KeeperHub webhook", "live wallet"],
        },
        "project": {
            "name": "Agent Bazaar",
            "tagline": "AI task exchange for idle agent capacity",
        },
        "rfq": {
            "id": rfq.rfq_id,
            "buyer_label": "Research Buyer",
            "buyer": rfq.buyer_agent_id,
            "task_type": rfq.task.type,
            "prompt": rfq.task.input["prompt"],
            "pair": rfq.task.input["pair"],
            "budget_atomic": rfq.budget.max_usdc_atomic,
            "accepted_tokens": rfq.budget.accepted_tokens,
            "min_reputation": rfq.constraints.min_reputation_score,
            "deadline_unix": rfq.constraints.deadline_unix,
        },
        "quotes": [
            {
                "seller": item.quote.seller_agent_id,
                "seller_label": [
                    "Efficient Price Agent",
                    "Fast Data Agent",
                    "Untested Low-Cost Agent",
                ][index],
                "price_atomic": item.quote.quote_price_atomic,
                "confidence": item.quote.confidence_score,
                "success_rate": item.quote.erc8004_reputation.success_rate,
                "total_tasks": item.quote.erc8004_reputation.total_tasks,
                "estimated_delivery_ms": item.quote.estimated_delivery_ms,
                "score": item.score if item.score != float("-inf") else None,
                "status": "eligible" if item.score != float("-inf") else "rejected",
                "reason": item.reason,
                "selected": item.quote.seller_agent_id == winner.seller_agent_id,
            }
            for index, item in enumerate(ranked)
        ],
        "matching": {
            "formula": "confidence * reputation / price",
            "winner": winner.seller_agent_id,
            "winner_reason": "best eligible reputation-weighted price",
        },
        "delivery": {
            "content": content,
            "result_hash": result_hash,
            "verified": True,
            "verification": "canonical JSON hash matched seller commitment",
        },
        "proofs": {
            "uniswap_quote_id": "52cdda69-9996-4b58-9101-d1451f44d8f0",
            "keeperhub_lock_execution": "ibah7qj9w7hhbrgho35az",
            "keeperhub_release_execution": "s7h6f1ovv98tt113gq7d5",
            "keeperhub_refund_execution": "mekgig98lj7vbumrmqiph",
            "escrow_address": "0x03C71Cf61c066479904A1800e2DCaf832ba59B1E",
            "mock_usdc_address": "0x8F8De0c9885267F715673F8932482981a98405f8",
            "erc8004_identity": "0xD966F2F92543938e26b3376DD8c60F047F226242",
            "erc8004_reputation": "0xEFD0c238D18188df7599E403C3DBdBba56C1e4b5",
            "feedback_tx": "0x691486874b1a7b64f2ac7f337e9e97657676fe9b8bac90bec44ee72377f7d9d0",
        },
        "timeline": [
            {
                "label": "Buyer asks for work",
                "layer": "Gensyn AXL",
                "detail": "Research Buyer broadcasts a data task to seller agents.",
                "state": "complete",
            },
            {
                "label": "Sellers bid",
                "layer": "Agent market",
                "detail": "Three agents answer with price, confidence, and reputation.",
                "state": "complete",
            },
            {
                "label": "Buyer picks one",
                "layer": "Matching",
                "detail": "The buyer selects the best score instead of a hardcoded worker.",
                "state": "complete",
            },
            {
                "label": "Funds locked",
                "layer": "KeeperHub + escrow",
                "detail": "Payment is reserved for the winner before work begins.",
                "state": "complete",
            },
            {
                "label": "Seller delivers",
                "layer": "Content hash",
                "detail": "The seller returns data and the buyer checks the content hash.",
                "state": "complete",
            },
            {
                "label": "Funds released",
                "layer": "KeeperHub",
                "detail": "Optimistic release pays the seller.",
                "state": "complete",
            },
            {
                "label": "Reputation updated",
                "layer": "ERC-8004",
                "detail": "Buyer feedback affects future matching.",
                "state": "complete",
            },
        ],
    }


def write_trace(output: Path) -> None:
    trace = build_market_trace()
    output.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(trace, indent=2, sort_keys=True)
    output.write_text(f"window.MARKET_TRACE = {payload};\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    write_trace(args.output)
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
